import express from "express";
import { createServer as createViteServer } from "vite";
import nodemailer from "nodemailer";
import dotenv from "dotenv";
import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";

dotenv.config();

type ApplicationPayload = {
  name?: string;
  email?: string;
  message?: string;
  website?: string;
};

type StoredApplication = {
  id: string;
  name: string;
  email: string;
  message: string;
  submittedAt: string;
  ipHash: string;
  userAgent: string;
  notificationStatus: "sent" | "failed" | "skipped";
  notificationError?: string;
};

const PORT = Number(process.env.PORT || 3000);
const DATA_DIR = process.env.DATA_DIR || path.join(process.cwd(), "data");
const APPLICATIONS_FILE = path.join(DATA_DIR, "applications.jsonl");
const MAINTENANCE_LOG_FILE = path.join(DATA_DIR, "maintenance.log");
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || "qian.917@osu.edu";
const EMAIL_FROM = process.env.EMAIL_FROM || process.env.EMAIL_USER;
const MAINTENANCE_INTERVAL_MS = Number(process.env.MAINTENANCE_INTERVAL_MS || 1000 * 60 * 60);
const MAX_APPLICATION_FILE_BYTES = Number(process.env.MAX_APPLICATION_FILE_BYTES || 1024 * 1024 * 5);
const RATE_LIMIT_WINDOW_MS = Number(process.env.RATE_LIMIT_WINDOW_MS || 1000 * 60 * 10);
const RATE_LIMIT_MAX = Number(process.env.RATE_LIMIT_MAX || 5);
const requestLog = new Map<string, number[]>();

function normalizeString(value: unknown, maxLength: number) {
  return typeof value === "string" ? value.trim().slice(0, maxLength) : "";
}

function isValidEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function hashValue(value: string) {
  return crypto.createHash("sha256").update(value).digest("hex");
}

function getClientKey(req: express.Request) {
  const forwardedFor = req.headers["x-forwarded-for"];
  const ip = Array.isArray(forwardedFor) ? forwardedFor[0] : forwardedFor?.split(",")[0];
  return ip?.trim() || req.ip || "unknown";
}

function isRateLimited(key: string) {
  const now = Date.now();
  const recent = (requestLog.get(key) || []).filter((timestamp) => now - timestamp < RATE_LIMIT_WINDOW_MS);
  recent.push(now);
  requestLog.set(key, recent);
  return recent.length > RATE_LIMIT_MAX;
}

async function ensureDataDirectory() {
  await fs.mkdir(DATA_DIR, { recursive: true });
}

async function appendJsonLine(filePath: string, value: unknown) {
  await ensureDataDirectory();
  await fs.appendFile(filePath, `${JSON.stringify(value)}\n`, "utf8");
}

async function appendMaintenanceLog(message: string) {
  await ensureDataDirectory();
  await fs.appendFile(MAINTENANCE_LOG_FILE, `[${new Date().toISOString()}] ${message}\n`, "utf8");
}

function createTransporter() {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS || !EMAIL_FROM) {
    return null;
  }

  return nodemailer.createTransport({
    service: process.env.EMAIL_SERVICE || "gmail",
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });
}

async function notifyAdmin(application: StoredApplication) {
  const transporter = createTransporter();

  if (!transporter) {
    return { status: "skipped" as const, error: "Email credentials are not configured." };
  }

  try {
    await transporter.sendMail({
      from: `"BMMSS Website" <${EMAIL_FROM}>`,
      replyTo: application.email,
      to: ADMIN_EMAIL,
      subject: `New BMMSS Application: ${application.name}`,
      text: [
        "New application received for BMMSS.",
        "",
        `Name: ${application.name}`,
        `Email: ${application.email}`,
        `Submitted: ${application.submittedAt}`,
        "",
        "Message / Background:",
        application.message || "(No additional message provided.)",
        "",
        `Application ID: ${application.id}`,
        "",
        "This email was automatically generated by the BMMSS website.",
      ].join("\n"),
    });

    return { status: "sent" as const };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown email error";
    return { status: "failed" as const, error: message };
  }
}

async function runMaintenance() {
  const now = Date.now();

  for (const [key, timestamps] of requestLog.entries()) {
    const recent = timestamps.filter((timestamp) => now - timestamp < RATE_LIMIT_WINDOW_MS);
    if (recent.length > 0) {
      requestLog.set(key, recent);
    } else {
      requestLog.delete(key);
    }
  }

  await ensureDataDirectory();

  try {
    const stats = await fs.stat(APPLICATIONS_FILE);
    if (stats.size > MAX_APPLICATION_FILE_BYTES) {
      const archiveName = `applications-${new Date().toISOString().replace(/[:.]/g, "-")}.jsonl`;
      await fs.rename(APPLICATIONS_FILE, path.join(DATA_DIR, archiveName));
      await appendMaintenanceLog(`Archived application log as ${archiveName}.`);
    } else {
      await appendMaintenanceLog(`Maintenance complete. Application log size: ${stats.size} bytes.`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      await appendMaintenanceLog("Maintenance complete. No application log exists yet.");
      return;
    }

    throw error;
  }
}

function startMaintenanceJob() {
  runMaintenance().catch((error) => {
    console.error("Maintenance error:", error);
  });

  setInterval(() => {
    runMaintenance().catch((error) => {
      console.error("Maintenance error:", error);
    });
  }, MAINTENANCE_INTERVAL_MS);
}

async function startServer() {
  const app = express();

  app.use(express.json());

  // API route for application submission
  app.post("/api/apply", async (req, res) => {
    const { name, email, message, website } = req.body as ApplicationPayload;
    const normalizedName = normalizeString(name, 120);
    const normalizedEmail = normalizeString(email, 180).toLowerCase();
    const normalizedMessage = normalizeString(message, 2000);
    const clientKey = getClientKey(req);

    if (website) {
      return res.status(200).json({ success: "Application submitted successfully!" });
    }

    if (isRateLimited(clientKey)) {
      return res.status(429).json({ error: "Too many submissions. Please wait a few minutes and try again." });
    }

    if (!normalizedName || !normalizedEmail) {
      return res.status(400).json({ error: "Name and email are required." });
    }

    if (!isValidEmail(normalizedEmail)) {
      return res.status(400).json({ error: "Please enter a valid email address." });
    }

    const application: StoredApplication = {
      id: crypto.randomUUID(),
      name: normalizedName,
      email: normalizedEmail,
      message: normalizedMessage,
      submittedAt: new Date().toISOString(),
      ipHash: hashValue(clientKey),
      userAgent: normalizeString(req.headers["user-agent"], 300),
      notificationStatus: "skipped",
    };

    try {
      const notification = await notifyAdmin(application);
      application.notificationStatus = notification.status;
      application.notificationError = notification.error;

      await appendJsonLine(APPLICATIONS_FILE, application);

      if (notification.status === "failed") {
        console.error("Email error:", notification.error);
        return res.status(202).json({
          success: "Application submitted successfully. The site saved your application, but admin email delivery needs attention.",
        });
      }

      res.status(200).json({ success: "Application submitted successfully!" });
    } catch (error) {
      console.error("Application submission error:", error);
      res.status(500).json({ error: "Failed to submit application. Please try again later." });
    }
  });

  app.get("/api/health", (_req, res) => {
    res.status(200).json({ ok: true, maintenanceIntervalMs: MAINTENANCE_INTERVAL_MS });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // Serve static files in production
    app.use(express.static("dist"));
    app.get(/.*/, (req, res) => {
      res.sendFile("dist/index.html", { root: "." });
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });

  startMaintenanceJob();
}

startServer();
